<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="LanguageExt.Core" Version="5.0.0-beta-77" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.11" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="LanguageExt" />
		<Using Include="LanguageExt.Prelude" Static="true" />
	</ItemGroup>

</Project>
